### PR TITLE
Fix release time parsing

### PR DESCRIPTION
**Pull request by DarkaMaul**
Quick fix for the CI failure.

Of note, the format with "Z" should be accepted [doc](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat)

### CODE REVIEW

**Comment by woodruffw** [comment]
Hmm, where did the CI fail? I believe we're now only running with the latest CPython, since `Z` wasn't well-supported on older versions.

**Comment by DarkaMaul** [comment]
For instance here: https://github.com/trailofbits/are-we-pep740-yet/actions/runs/11674169517/job/32506361127
(And during my local tests)


(Another option would be force the script to run with Python 3.11+)

**Comment by woodruffw** [comment]
> (Another option would be force the script to run with Python 3.11+)

Yeah, that's what the CI currently does:

https://github.com/trailofbits/are-we-pep740-yet/commit/a164078b4d13531288d496d2ec7cb4bb62bb31a9

I think I'd prefer we just mandate 3.11+ rather than mucking with the time formats 🙂 -- could you send a PR adding `.python-version` for that?

**Comment by woodruffw** [comment]
Thanks @DarkaMaul!

**Pull request merged**
